Add GitHub Actions workflow to update docker image used in pass-docker when pass-core is updated
eclipse-pass/pass-core pull request #10
Opened 2022-11-08 15:47 UTC by grant-mcs

2022-11-08 18:50 UTC, aforward approved these changes

2022-11-10 15:55 UTC, jabrah requested changes

2022-11-10 15:55 UTC, jabrah commented on .github/workflows/update-image.yml
> +        run: python tools/update-image.py eclipse-pass.nightly.yml pass-core "${{ steps.pom_version.outputs.POM_VERSION }}@${{ steps.image_hash.outputs.IMAGE_HASH }}"
The image in `eclipse-pass.nightly.yml` should be called `pass-core-main`

There's a reference in [`eclipse-pass.nightly.yml` that references `pass-core`](https://github.com/eclipse-pass/pass-docker/blob/main/eclipse-pass.nightly.yml#L13) which is spiking new builds. Looks like this is coming from this Action

2022-11-10 16:10 UTC, grant-mcs commented on .github/workflows/update-image.yml
> +        run: python tools/update-image.py eclipse-pass.nightly.yml pass-core "${{ steps.pom_version.outputs.POM_VERSION }}@${{ steps.image_hash.outputs.IMAGE_HASH }}"
Good point! I've updated this call to include the full path to the image instead of letting it use the default which assumes the image name matches the service name.

2022-11-10 16:24 UTC, jabrah approved these changes
✅

2022-11-10 16:28 UTC, merged